// Mapa compartilhado: id do time (data/teams.ts) -> nomes de busca no TheSportsDB.
// Usado por fetch-crests.mjs e fetch-squads.mjs.
export const ID_OVERRIDE = {
  psg: '133714', // Paris Saint-Germain (busca por nome não acha o time masculino)
  nottingham: '133720' // Nottingham Forest (busca por nome não retorna)
}

export const TEAMS = {
  // Clubes europeus
  'real-madrid': ['Real Madrid'],
  'man-city': ['Manchester City'],
  bayern: ['Bayern Munich', 'Bayern München'],
  barcelona: ['Barcelona'],
  psg: ['Paris Saint-Germain', 'Paris SG'],
  liverpool: ['Liverpool'],
  inter: ['Inter Milan', 'Internazionale'],
  arsenal: ['Arsenal'],
  atletico: ['Atletico Madrid'],
  dortmund: ['Borussia Dortmund'],
  milan: ['AC Milan'],
  juventus: ['Juventus'],
  'man-united': ['Manchester United'],
  chelsea: ['Chelsea'],
  napoli: ['Napoli'],
  tottenham: ['Tottenham Hotspur', 'Tottenham'],
  // Clubes brasileiros
  flamengo: ['Flamengo'],
  palmeiras: ['Palmeiras'],
  'atletico-mg': ['Atletico Mineiro', 'Atletico-MG'],
  fluminense: ['Fluminense'],
  'sao-paulo': ['Sao Paulo'],
  corinthians: ['Corinthians'],
  internacional: ['Internacional'],
  gremio: ['Gremio'],
  botafogo: ['Botafogo'],
  cruzeiro: ['Cruzeiro'],
  'athletico-pr': ['Athletico Paranaense', 'Atletico Paranaense'],
  santos: ['Santos'],
  // Seleções
  brasil: ['Brazil'],
  franca: ['France'],
  argentina: ['Argentina'],
  espanha: ['Spain'],
  inglaterra: ['England'],
  alemanha: ['Germany'],
  portugal: ['Portugal'],
  holanda: ['Netherlands'],
  italia: ['Italy'],
  belgica: ['Belgium'],
  croacia: ['Croatia'],
  uruguai: ['Uruguay'],
  colombia: ['Colombia'],
  marrocos: ['Morocco'],
  mexico: ['Mexico'],
  eua: ['USA', 'United States'],
  japao: ['Japan'],
  senegal: ['Senegal'],
  suica: ['Switzerland'],
  dinamarca: ['Denmark'],
  coreia: ['South Korea', 'Korea Republic'],
  servia: ['Serbia'],
  equador: ['Ecuador'],
  australia: ['Australia'],
  // +50 clubes
  newcastle: ['Newcastle'],
  'aston-villa': ['Aston Villa'],
  'west-ham': ['West Ham United'],
  brighton: ['Brighton'],
  everton: ['Everton'],
  nottingham: ['Nottingham Forest'],
  wolves: ['Wolverhampton Wanderers', 'Wolves'],
  'crystal-palace': ['Crystal Palace'],
  fulham: ['Fulham'],
  leeds: ['Leeds United'],
  sevilla: ['Sevilla'],
  betis: ['Real Betis', 'Betis'],
  villarreal: ['Villarreal'],
  'real-sociedad': ['Real Sociedad'],
  athletic: ['Athletic Bilbao', 'Athletic Club'],
  valencia: ['Valencia'],
  celta: ['Celta Vigo', 'Celta de Vigo'],
  roma: ['AS Roma', 'Roma'],
  lazio: ['Lazio'],
  atalanta: ['Atalanta'],
  fiorentina: ['Fiorentina'],
  bologna: ['Bologna'],
  torino: ['Torino'],
  leipzig: ['RB Leipzig'],
  leverkusen: ['Bayer Leverkusen', 'Leverkusen'],
  frankfurt: ['Eintracht Frankfurt'],
  stuttgart: ['VfB Stuttgart', 'Stuttgart'],
  gladbach: ['Borussia Monchengladbach', 'Monchengladbach'],
  marseille: ['Marseille', 'Olympique Marseille'],
  lyon: ['Lyon', 'Olympique Lyonnais'],
  monaco: ['Monaco', 'AS Monaco'],
  lille: ['Lille OSC', 'Lille'],
  nice: ['Nice', 'OGC Nice'],
  benfica: ['Benfica'],
  porto: ['Porto', 'FC Porto'],
  sporting: ['Sporting CP', 'Sporting Lisbon'],
  braga: ['Sporting Braga', 'Braga'],
  ajax: ['Ajax'],
  psv: ['PSV Eindhoven', 'PSV'],
  feyenoord: ['Feyenoord'],
  celtic: ['Celtic'],
  rangers: ['Rangers'],
  galatasaray: ['Galatasaray'],
  fenerbahce: ['Fenerbahce'],
  boca: ['Boca Juniors'],
  river: ['River Plate'],
  vasco: ['Vasco da Gama', 'Vasco'],
  bahia: ['Bahia', 'EC Bahia'],
  fortaleza: ['Fortaleza', 'Fortaleza EC'],
  'america-mx': ['Club America', 'America']
}
