// Mapa compartilhado: id do time (data/teams.ts) -> nomes de busca no TheSportsDB.
// Usado por fetch-crests.mjs e fetch-squads.mjs.
export const ID_OVERRIDE = {
  psg: '133714', // Paris Saint-Germain (busca por nome não acha o time masculino)
  nottingham: '133720' // Nottingham Forest (busca por nome não retorna)
}

export const TEAMS = {
  // Clubes europeus
  'real-madrid': ['Real Madrid'],
  'man-city': ['Manchester City'],
  bayern: ['Bayern Munich', 'Bayern München'],
  barcelona: ['Barcelona'],
  psg: ['Paris Saint-Germain', 'Paris SG'],
  liverpool: ['Liverpool'],
  inter: ['Inter Milan', 'Internazionale'],
  arsenal: ['Arsenal'],
  atletico: ['Atletico Madrid'],
  dortmund: ['Borussia Dortmund'],
  milan: ['AC Milan'],
  juventus: ['Juventus'],
  'man-united': ['Manchester United'],
  chelsea: ['Chelsea'],
  napoli: ['Napoli'],
  tottenham: ['Tottenham Hotspur', 'Tottenham'],
  // Clubes brasileiros
  flamengo: ['Flamengo'],
  palmeiras: ['Palmeiras'],
  'atletico-mg': ['Atletico Mineiro', 'Atletico-MG'],
  fluminense: ['Fluminense'],
  'sao-paulo': ['Sao Paulo'],
  corinthians: ['Corinthians'],
  internacional: ['Internacional'],
  gremio: ['Gremio'],
  botafogo: ['Botafogo'],
  cruzeiro: ['Cruzeiro'],
  'athletico-pr': ['Athletico Paranaense', 'Atletico Paranaense'],
  santos: ['Santos'],
  // Seleções
  brasil: ['Brazil'],
  franca: ['France'],
  argentina: ['Argentina'],
  espanha: ['Spain'],
  inglaterra: ['England'],
  alemanha: ['Germany'],
  portugal: ['Portugal'],
  holanda: ['Netherlands'],
  italia: ['Italy'],
  belgica: ['Belgium'],
  croacia: ['Croatia'],
  uruguai: ['Uruguay'],
  colombia: ['Colombia'],
  marrocos: ['Morocco'],
  mexico: ['Mexico'],
  eua: ['USA', 'United States'],
  japao: ['Japan'],
  senegal: ['Senegal'],
  suica: ['Switzerland'],
  dinamarca: ['Denmark'],
  coreia: ['South Korea', 'Korea Republic'],
  servia: ['Serbia'],
  equador: ['Ecuador'],
  australia: ['Australia'],
  // +50 clubes
  newcastle: ['Newcastle'],
  'aston-villa': ['Aston Villa'],
  'west-ham': ['West Ham United'],
  brighton: ['Brighton'],
  everton: ['Everton'],
  nottingham: ['Nottingham Forest'],
  wolves: ['Wolverhampton Wanderers', 'Wolves'],
  'crystal-palace': ['Crystal Palace'],
  fulham: ['Fulham'],
  leeds: ['Leeds United'],
  sevilla: ['Sevilla'],
  betis: ['Real Betis', 'Betis'],
  villarreal: ['Villarreal'],
  'real-sociedad': ['Real Sociedad'],
  athletic: ['Athletic Bilbao', 'Athletic Club'],
  valencia: ['Valencia'],
  celta: ['Celta Vigo', 'Celta de Vigo'],
  roma: ['AS Roma', 'Roma'],
  lazio: ['Lazio'],
  atalanta: ['Atalanta'],
  fiorentina: ['Fiorentina'],
  bologna: ['Bologna'],
  torino: ['Torino'],
  leipzig: ['RB Leipzig'],
  leverkusen: ['Bayer Leverkusen', 'Leverkusen'],
  frankfurt: ['Eintracht Frankfurt'],
  stuttgart: ['VfB Stuttgart', 'Stuttgart'],
  gladbach: ['Borussia Monchengladbach', 'Monchengladbach'],
  marseille: ['Marseille', 'Olympique Marseille'],
  lyon: ['Lyon', 'Olympique Lyonnais'],
  monaco: ['Monaco', 'AS Monaco'],
  lille: ['Lille OSC', 'Lille'],
  nice: ['Nice', 'OGC Nice'],
  benfica: ['Benfica'],
  porto: ['Porto', 'FC Porto'],
  sporting: ['Sporting CP', 'Sporting Lisbon'],
  braga: ['Sporting Braga', 'Braga'],
  ajax: ['Ajax'],
  psv: ['PSV Eindhoven', 'PSV'],
  feyenoord: ['Feyenoord'],
  celtic: ['Celtic'],
  rangers: ['Rangers'],
  galatasaray: ['Galatasaray'],
  fenerbahce: ['Fenerbahce'],
  boca: ['Boca Juniors'],
  river: ['River Plate'],
  vasco: ['Vasco da Gama', 'Vasco'],
  bahia: ['Bahia', 'EC Bahia'],
  fortaleza: ['Fortaleza', 'Fortaleza EC'],
  'america-mx': ['Club America', 'America'],
  // ---- CONMEBOL — clubes sul-americanos ----
  'colo-colo': ['Colo-Colo', 'CSD Colo-Colo'],
  'u-de-chile': ['Universidad de Chile', 'U de Chile'],
  'u-catolica': ['Universidad Catolica', 'CD Universidad Catolica'],
  penarol: ['Penarol', 'CA Penarol'],
  'nacional-uy': ['Nacional', 'Club Nacional de Football'],
  olimpia: ['Olimpia', 'Club Olimpia'],
  'cerro-porteno': ['Cerro Porteno', 'Club Cerro Porteno'],
  'atletico-nacional': ['Atletico Nacional', 'Atl. Nacional'],
  millonarios: ['Millonarios', 'Millonarios FC'],
  'america-cali': ['America de Cali'],
  'barcelona-sc': ['Barcelona SC', 'Barcelona Sporting Club'],
  'ldu-quito': ['LDU Quito', 'Liga de Quito', 'Liga Deportiva Universitaria'],
  'independiente-del-valle': ['Independiente del Valle'],
  universitario: ['Universitario', 'Universitario de Deportes'],
  'alianza-lima': ['Alianza Lima', 'Club Alianza Lima'],
  bolivar: ['Bolivar', 'Club Bolivar'],
  'the-strongest': ['The Strongest', 'Club The Strongest'],
  'deportivo-tachira': ['Deportivo Tachira'],
  'caracas-fc': ['Caracas FC', 'Caracas'],
  // ---- CONMEBOL — ligas nacionais completas ----
  // Argentina
  lanus: ['Lanus', 'CA Lanus'],
  'rosario-central': ['Rosario Central'],
  'argentinos-jrs': ['Argentinos Juniors'],
  newells: ['Newells Old Boys', "Newell's Old Boys"],
  'defensa-justicia': ['Defensa y Justicia'],
  'godoy-cruz': ['Godoy Cruz'],
  belgrano: ['Belgrano', 'CA Belgrano'],
  banfield: ['Banfield', 'CA Banfield'],
  'gimnasia-lp': ['Gimnasia La Plata', 'Gimnasia y Esgrima La Plata'],
  instituto: ['Instituto', 'Instituto de Cordoba'],
  'atletico-tucuman': ['Atletico Tucuman'],
  'union-santa-fe': ['Union Santa Fe', 'Union de Santa Fe'],
  'central-cordoba': ['Central Cordoba', 'Central Cordoba SdE'],
  tigre: ['Tigre', 'CA Tigre'],
  platense: ['Platense', 'CA Platense'],
  'independiente-riv': ['Independiente Rivadavia'],
  'barracas-central': ['Barracas Central'],
  sarmiento: ['Sarmiento', 'Sarmiento de Junin'],
  'deportivo-riestra': ['Deportivo Riestra'],
  aldosivi: ['Aldosivi'],
  'san-martin-sj': ['San Martin San Juan', 'San Martin de San Juan'],
  // Chile
  'coquimbo-unido': ['Coquimbo Unido'],
  ohiggins: ["O'Higgins", 'OHiggins'],
  palestino: ['Palestino', 'CD Palestino'],
  cobresal: ['Cobresal', 'CD Cobresal'],
  'audax-italiano': ['Audax Italiano'],
  'union-espanola': ['Union Espanola'],
  huachipato: ['Huachipato', 'CD Huachipato'],
  'everton-cl': ['Everton de Vina del Mar', 'Everton Vina del Mar'],
  nublense: ['Nublense', 'CD Nublense'],
  'union-la-calera': ['Union La Calera'],
  'deportes-iquique': ['Deportes Iquique'],
  'la-serena': ['Deportes La Serena', 'La Serena'],
  'deportes-limache': ['Deportes Limache'],
  // Uruguai
  'defensor-sporting': ['Defensor Sporting'],
  'liverpool-uy': ['Liverpool Montevideo', 'Liverpool FC Montevideo'],
  danubio: ['Danubio', 'Danubio FC'],
  'wanderers-uy': ['Montevideo Wanderers'],
  'river-uy': ['River Plate Montevideo', 'CA River Plate Montevideo'],
  'boston-river': ['Boston River'],
  'cerro-largo': ['Cerro Largo'],
  torque: ['Montevideo City Torque', 'Torque'],
  'cerro-uy': ['CA Cerro', 'Cerro Montevideo'],
  'racing-uy': ['Racing Club de Montevideo', 'Racing Montevideo'],
  'plaza-colonia': ['Plaza Colonia'],
  'juventud-uy': ['Juventud de Las Piedras', 'Juventud Las Piedras'],
  'miramar-misiones': ['Miramar Misiones'],
  progreso: ['Progreso', 'CA Progreso'],
  // Paraguai
  libertad: ['Libertad', 'Club Libertad'],
  'guarani-py': ['Guarani Asuncion', 'Club Guarani'],
  'nacional-py': ['Nacional Asuncion', 'Club Nacional Asuncion'],
  'sportivo-luqueno': ['Sportivo Luqueno'],
  'sportivo-trinidense': ['Sportivo Trinidense'],
  'sportivo-ameliano': ['Sportivo Ameliano'],
  tacuary: ['Tacuary', 'Tacuary FC'],
  'dos-de-mayo': ['2 de Mayo', 'Club 2 de Mayo'],
  'general-caballero': ['General Caballero JLM', 'General Caballero'],
  recoleta: ['Recoleta', 'Recoleta FC'],
  // Colômbia
  'junior-barranquilla': ['Junior', 'Junior de Barranquilla', 'Atletico Junior'],
  'santa-fe': ['Independiente Santa Fe', 'Santa Fe'],
  'independiente-medellin': ['Independiente Medellin'],
  tolima: ['Deportes Tolima'],
  'deportivo-cali': ['Deportivo Cali'],
  'once-caldas': ['Once Caldas'],
  bucaramanga: ['Atletico Bucaramanga'],
  pereira: ['Deportivo Pereira'],
  'aguilas-doradas': ['Aguilas Doradas', 'Rionegro Aguilas'],
  'la-equidad': ['La Equidad'],
  envigado: ['Envigado', 'Envigado FC'],
  'deportivo-pasto': ['Deportivo Pasto'],
  'alianza-fc': ['Alianza FC', 'Alianza Petrolera'],
  'fortaleza-ceif': ['Fortaleza CEIF'],
  'boyaca-chico': ['Boyaca Chico'],
  'union-magdalena': ['Union Magdalena'],
  llaneros: ['Llaneros', 'Llaneros FC'],
  // Equador
  emelec: ['Emelec', 'CS Emelec'],
  aucas: ['Aucas', 'SD Aucas'],
  'u-catolica-ec': ['Universidad Catolica Quito', 'Universidad Catolica del Ecuador'],
  'el-nacional': ['El Nacional', 'CD El Nacional'],
  delfin: ['Delfin', 'Delfin SC'],
  'deportivo-cuenca': ['Deportivo Cuenca'],
  orense: ['Orense', 'Orense SC'],
  macara: ['Macara', 'CSD Macara'],
  'mushuc-runa': ['Mushuc Runa'],
  'tecnico-universitario': ['Tecnico Universitario'],
  'libertad-ec': ['Libertad FC', 'Libertad Loja'],
  'manta-fc': ['Manta', 'Manta FC'],
  'vinotinto-ec': ['Vinotinto', 'Vinotinto Ecuador'],
  // Peru
  'sporting-cristal': ['Sporting Cristal'],
  melgar: ['Melgar', 'FBC Melgar'],
  cienciano: ['Cienciano'],
  'cusco-fc': ['Cusco', 'Cusco FC'],
  'sport-huancayo': ['Sport Huancayo'],
  'deportivo-garcilaso': ['Deportivo Garcilaso'],
  'atletico-grau': ['Atletico Grau'],
  adt: ['ADT', 'ADT Tarma'],
  'sport-boys': ['Sport Boys'],
  utc: ['UTC', 'UTC Cajamarca'],
  'alianza-atletico': ['Alianza Atletico'],
  'los-chankas': ['Los Chankas'],
  binacional: ['Binacional', 'Deportivo Binacional'],
  'ayacucho-fc': ['Ayacucho', 'Ayacucho FC'],
  'comerciantes-unidos': ['Comerciantes Unidos'],
  'juan-pablo-ii': ['Juan Pablo II'],
  // Bolívia
  'always-ready': ['Always Ready'],
  blooming: ['Blooming'],
  'oriente-petrolero': ['Oriente Petrolero'],
  wilstermann: ['Jorge Wilstermann', 'Wilstermann'],
  'nacional-potosi': ['Nacional Potosi'],
  guabira: ['Guabira'],
  'san-antonio-bb': ['San Antonio Bulo Bulo'],
  'real-tomayapo': ['Real Tomayapo'],
  'aurora-bo': ['Aurora', 'Club Aurora'],
  'gv-san-jose': ['GV San Jose', 'San Jose Oruro'],
  'independiente-petrolero': ['Independiente Petrolero'],
  'universitario-vinto': ['Universitario de Vinto'],
  'real-oruro': ['Real Oruro'],
  'real-santa-cruz': ['Real Santa Cruz'],
  // Venezuela
  'academia-puerto-cabello': ['Academia Puerto Cabello'],
  'deportivo-la-guaira': ['Deportivo La Guaira'],
  metropolitanos: ['Metropolitanos', 'Metropolitanos FC'],
  'estudiantes-merida': ['Estudiantes de Merida'],
  carabobo: ['Carabobo', 'Carabobo FC'],
  'zamora-fc': ['Zamora', 'Zamora FC'],
  monagas: ['Monagas', 'Monagas SC'],
  'portuguesa-fc': ['Portuguesa FC'],
  mineros: ['Mineros de Guayana', 'Mineros'],
  ucv: ['UCV FC', 'Universidad Central de Venezuela'],
  'rayo-zuliano': ['Rayo Zuliano'],
  angostura: ['Angostura', 'Angostura FC'],
  // Seleções CONMEBOL fora da Copa 2026
  chile: ['Chile'],
  peru: ['Peru'],
  venezuela: ['Venezuela'],
  bolivia: ['Bolivia']
}
